import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';

const Post: NextPage = () => {
  const router = useRouter();
  const { id } = router.query;
  return (
    <div>
      <Head>
        <title>Posts | PSM</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <p>{id}</p>
    </div>
  );
};

export default Post;
