import type { NextPage } from 'next';
import Head from 'next/head';

const AboutUs: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Nosotros | Proyectos San Marcos</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </div>
  );
};

export default AboutUs;
