import type { NextPage } from 'next';
import Head from 'next/head';

import Footer from '@components/containers/Footer';
import Header from '@components/containers/Header';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Home | Proyectos San Marcos</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Footer />
    </div>
  );
};

export default Home;
