import type { NextPage } from 'next';
import Head from 'next/head';

import Header from '@components/containers/Header';

const Profile: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Profile | Proyectos San Marcos</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
    </div>
  );
};

export default Profile;
