import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';

import Header from '../../components/containers/Header';

const Course: NextPage = () => {
  const router = useRouter();
  const { id } = router.query;
  return (
    <div>
      <Head>
        <title>Cursos | PSM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <p>{id}</p>
    </div>
  )
}

export default Course;
