import type { NextPage } from 'next';
import Head from 'next/head';

import Header from '@components/containers/Header';

const CoursePage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Cursos | Proyectos San Marcos</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <p>¡Hola, bienvenido a los cursos de PSM!</p>
    </div>
  );
};

export default CoursePage;
