import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';

const Management: NextPage = () => {
  const router = useRouter();
  const { name } = router.query;
  return (
    <div>
      <Head>
        <title>Gerencia :name | PSM</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <p>{name}</p>
    </div>
  );
};

export default Management;
